import type { User, Video, Notification } from './types'
import { Timestamp } from 'firebase/firestore'

const mockTimestamp = Timestamp.fromDate(new Date('2025-01-01T00:00:00.000Z'))

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Neysha',
    username: '@neysha',
    avatarUrl: 'https://picsum.photos/seed/101/200/200',
    following: 150,
    followers: 2500000,
    likes: 10200000,
    bio: 'Just for fun ✨ Living my best life.',
    role: 'creator',
    email: 'neysha@example.com',
    createdAt: mockTimestamp,
  },
  {
    id: '2',
    name: 'Alex Max',
    username: '@alexmax',
    avatarUrl: 'https://picsum.photos/seed/102/200/200',
    following: 320,
    followers: 120000,
    likes: 5400000,
    bio: 'Creator | Dancer | Tech Geek',
    role: 'creator',
    email: 'alex@example.com',
    createdAt: mockTimestamp,
  },
  {
    id: '3',
    name: 'CreativeFlow',
    username: '@creativeflow',
    avatarUrl: 'https://picsum.photos/seed/103/200/200',
    following: 500,
    followers: 890000,
    likes: 12000000,
    bio: 'Art and technology combined. Follow for daily inspiration.',
    role: 'creator',
    email: 'creative@example.com',
    createdAt: mockTimestamp,
  },
]

export const mockVideos: Video[] = [
  {
    id: 'v1',
    user: mockUsers[0],
    videoUrl: 'https://res.cloudinary.com/dy73hzkpm/video/upload/v1721320498/pexels-maksim-goncharenok-6458406_1080p_r6twd6.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/201/400/800',
    description: 'Amazing sunset view from my last trip! #travel #sunset #nature',
    song: 'Original Sound - @neysha',
    likes: 120000,
    comments: 3400,
    shares: 1200,
    createdAt: mockTimestamp,
  },
  {
    id: 'v2',
    user: mockUsers[1],
    videoUrl: 'https://res.cloudinary.com/dy73hzkpm/video/upload/v1721320494/pexels-polina-tankilevitch-5532840_1080p_jafj8e.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/202/400/800',
    description: 'New dance challenge! Can you do it? 🔥 #dancechallenge #hiphop',
    song: 'Upbeat Funk - AudioLibrary',
    likes: 450000,
    comments: 12000,
    shares: 8000,
    createdAt: mockTimestamp,
  },
  {
    id: 'v3',
    user: mockUsers[2],
    videoUrl: 'https://res.cloudinary.com/dy73hzkpm/video/upload/v1721320494/pexels-tima-miroshnichenko-6750381_1080p_qg2vj4.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/203/400/800',
    description: 'Building a cool new gadget. Sneak peek! #tech #diy #gadget',
    song: 'Tech House - CoolVibes',
    likes: 88000,
    comments: 1500,
    shares: 500,
    createdAt: mockTimestamp,
  },
  {
    id: 'v4',
    user: mockUsers[0],
    videoUrl: 'https://res.cloudinary.com/dy73hzkpm/video/upload/v1721320493/production_id-4428054_1080p_hzs9x5.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/204/400/800',
    description: 'Morning coffee routine ☕️ #coffee #morning #routine',
    song: 'Chill Lo-fi - Aesthetic Sounds',
    likes: 210000,
    comments: 7800,
    shares: 2300,
    createdAt: mockTimestamp,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    user: mockUsers[1],
    type: 'like',
    content: 'liked your video.',
    timestamp: '2h ago',
    read: false,
  },
  {
    id: 'n2',
    user: mockUsers[2],
    type: 'follow',
    content: 'started following you.',
    timestamp: '5h ago',
    read: false,
  },
  {
    id: 'n3',
    user: mockUsers[1],
    type: 'comment',
    content: 'commented: "This is amazing! 🔥"',
    timestamp: '1d ago',
    read: true,
  },
  {
    id: 'n4',
    user: mockUsers[2],
    type: 'like',
    content: 'liked your video.',
    timestamp: '2d ago',
    read: true,
  },
]
