// DO NOT MODIFY. This file is autogenerated
'use client';
import { useEffect, useState } from 'react';
import { onAuthStateChanged, type User } from 'firebase/auth';
import { useAuth } from '@/firebase/provider';

/**
 * A hook that returns the currently authenticated user.
 *
 * @returns An object containing the user, a loading state, and any error that occurred.
 *
 * @example
 * ```tsx
 * import { useUser } from '@/lib/auth';
 *
 * function UserProfile() {
 *  const { user, loading, error } = useUser();
 *
 *  if (loading) {
 *    return <div>Loading...</div>;
 *  }
 *
 *  if (error) {
 *    return <div>Error: {error.message}</div>;
 *  }
 *
 *  return <div>Welcome, {user?.displayName}</div>;
 * }
 * ```
 */
export function useUser() {
  const auth = useAuth();
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    if (!auth) {
      // This can happen if the hook is used outside of the FirebaseProvider.
      // We'll set loading to false and return early.
      setLoading(false);
      return;
    }

    const unsubscribe = onAuthStateChanged(
      auth,
      (user) => {
        setUser(user);
        setLoading(false);
      },
      (error) => {
        setError(error);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [auth]);

  return { user, loading, error };
}
