// DO NOT MODIFY. This file is autogenerated
'use client';
import { useEffect, useState } from 'react';
import {
  onSnapshot,
  query,
  collection,
  where,
  type DocumentData,
  type Firestore,
  type CollectionReference,
  type Query,
} from 'firebase/firestore';

import { useFirestore } from '@/firebase/provider';
import { errorEmitter } from '@/firebase/error-emitter';
import {
  FirestorePermissionError,
  type SecurityRuleContext,
} from '@/firebase/errors';

/**
 * A hook that listens to a collection and returns the data.
 *
 * @param path The path to the collection.
 * @returns An object containing the data, a loading state, and any error that occurred.
 *
 * @example
 * ```tsx
 * import { useCollection } from '@/lib/firestore';
 *
 * function Todos() {
 *  const { data, loading, error } = useCollection('todos');
 *
 * if (loading) {
 *   return <div>Loading...</div>;
 * }
 *
 * if (error) {
 *  return <div>Error: {error.message}</div>;
 * }
 *
 * return (
 *  <ul>
 *   {data.map((todo) => (
 *    <li key={todo.id}>{todo.title}</li>
 *  ))}
 * </ul>
 * );
 * }
 * ```
 */
export function useCollection<T = DocumentData>(
  q: Query<T> | CollectionReference<T> | null
) {
  const [data, setData] = useState<T[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);
  const firestore = useFirestore();

  useEffect(() => {
    if (!firestore || !q) {
      // This can happen if the hook is used outside of the FirebaseProvider
      // or if the query is not yet available.
      setLoading(false);
      return;
    }

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        const data = snapshot.docs.map((doc) => {
          return {
            ...doc.data(),
            id: doc.id,
          };
        });

        setData(data as T[]);
        setLoading(false);
      },
      (error) => {
        const permissionError = new FirestorePermissionError({
          path: q.path,
          operation: 'list',
        } satisfies SecurityRuleContext);

        errorEmitter.emit('permission-error', permissionError);
        setError(error);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [firestore, q]);

  return { data, loading, error };
}
