// DO NOT MODIFY. This file is autogenerated
'use client';
import { useEffect, useState } from 'react';
import {
  onSnapshot,
  doc,
  type DocumentData,
  type DocumentReference,
} from 'firebase/firestore';

import { useFirestore } from '@/firebase/provider';
import { errorEmitter } from '@/firebase/error-emitter';
import {
  FirestorePermissionError,
  type SecurityRuleContext,
} from '@/firebase/errors';

/**
 * A hook that listens to a document and returns the data.
 *
 * @param ref The reference to the document.
 * @returns An object containing the data, a loading state, and any error that occurred.
 *
 * @example
 * ```tsx
 * import { useDoc } from '@/lib/firestore';
 * import { doc } from 'firebase/firestore';
 *
 * function Todo({ id }: { id: string }) {
 * const ref = doc(useFirestore(), 'todos', id);
 * const { data, loading, error } = useDoc(ref);
 *
 * if (loading) {
 *  return <div>Loading...</div>;
 * }
 *
 * if (error) {
 * return <div>Error: {error.message}</div>;
 * }
 *
 * return <div>{data.title}</div>;
 * }
 * ```
 */
export function useDoc<T = DocumentData>(
  ref: DocumentReference<T> | null
) {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);
  const firestore = useFirestore();

  useEffect(() => {
    if (!firestore || !ref) {
      // This can happen if the hook is used outside of the FirebaseProvider
      // or if the reference is not yet available.
      setLoading(false);
      return;
    }

    const unsubscribe = onSnapshot(
      ref,
      (snapshot) => {
        if (snapshot.exists()) {
          setData({
            ...snapshot.data(),
            id: snapshot.id,
          } as T);
        } else {
          setData(null);
        }

        setLoading(false);
      },
      (error) => {
        const permissionError = new FirestorePermissionError({
          path: ref.path,
          operation: 'get',
        } satisfies SecurityRuleContext);

        errorEmitter.emit('permission-error', permissionError);
        setError(error);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [firestore, ref]);

  return { data, loading, error };
}
