// DO NOT MODIFY. This file is autogenerated
'use client';
import { initializeFirebase } from '.';
import { FirebaseProvider, type FirebaseContextValue } from './provider';
import { FirebaseErrorListener } from '@/components/FirebaseErrorListener';

let firebaseApp: FirebaseContextValue | null = null;

// This provider is used to initialize Firebase on the client side.
// It ensures that Firebase is initialized only once.
export function FirebaseClientProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  if (!firebaseApp) {
    firebaseApp = initializeFirebase();
  }

  return (
    <FirebaseProvider {...firebaseApp}>
      <FirebaseErrorListener />
      {children}
    </FirebaseProvider>
  );
}
