// DO NOT MODIFY. This file is autogenerated
//
// This file is automatically generated by the Firebase Studio.
//
// It contains the configuration for your Firebase project.
// You shouldn't need to edit it manually.
//
// Your Firebase project's configuration is managed by the Firebase Studio
// To view or change this configuration, open the Firebase panel in the Studio.

export const firebaseConfig = {
  "projectId": "studio-4725166594-b0358",
  "appId": "1:42990010526:web:b2167b12a7cd9a233cfb8f",
  "apiKey": "AIzaSyBVgR1qeDg_Z9eXc7mJ5WzprlvTCMhJr4o",
  "authDomain": "studio-4725166594-b0358.firebaseapp.com",
  "measurementId": "",
  "storageBucket": "studio-4725166594-b0358.appspot.com",
  "messagingSenderId": "42990010526"
};

if (typeof window !== 'undefined') {
  console.log('Firebase config loaded');
}
