// DO NOT MODIFY. This file is autogenerated
export type SecurityRuleContext = {
    path: string;
    operation: 'get' | 'list' | 'create' | 'update' | 'delete';
    requestResourceData?: any;
};

// A custom error class that will be thrown when a Firestore
// permission error occurs. It contains the context of the
// security rule that failed.
export class FirestorePermissionError extends Error {
    public context: SecurityRuleContext;
    
    constructor(context: SecurityRuleContext) {
        const { path, operation } = context;
        super(`Firestore permission denied on ${operation} for ${path}`);
        this.name = 'FirestorePermissionError';
        this.context = context;

        // This is a workaround for a bug in V8 that prevents
        // the stack trace from being correctly captured.
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, FirestorePermissionError);
        }
    }

    toJSON() {
        return {
            name: this.name,
            message: this.message,
            context: this.context,
            stack: this.stack,
        };
    }
}
