// DO NOT MODIFY. This file is autogenerated
import { FirestorePermissionError } from './errors';

type Events = {
  'permission-error': (error: FirestorePermissionError) => void;
};

// This is a simple event emitter that we use to broadcast
// Firestore permission errors to a global error listener.
class ErrorEmitter {
  private listeners: { [K in keyof Events]?: Events[K][] } = {};

  on<K extends keyof Events>(event: K, listener: Events[K]): () => void {
    if (!this.listeners[event]) {
      this.listeners[event] = [];
    }
    this.listeners[event]!.push(listener);
    return () => {
      this.off(event, listener);
    };
  }

  off<K extends keyof Events>(event: K, listener: Events[K]): void {
    if (!this.listeners[event]) {
      return;
    }
    const index = this.listeners[event]!.indexOf(listener);
    if (index > -1) {
      this.listeners[event]!.splice(index, 1);
    }
  }

  emit<K extends keyof Events>(event: K, ...args: Parameters<Events[K]>): void {
    if (!this.listeners[event]) {
      return;
    }
    this.listeners[event]!.forEach((listener) => {
      try {
        listener(...args);
      } catch (e) {
        console.error(`Error in listener for event "${event}":`, e);
      }
    });
  }
}

export const errorEmitter = new ErrorEmitter();
