// DO NOT MODIFY. This file is autogenerated
import { getApp, getApps, initializeApp } from 'firebase/app';
import { getAuth, connectAuthEmulator } from 'firebase/auth';
import { getFirestore, connectFirestoreEmulator } from 'firebase/firestore';
import { getStorage, connectStorageEmulator } from 'firebase/storage';
import { firebaseConfig } from './config';

import { useCollection } from './firestore/use-collection';
import { useDoc } from './firestore/use-doc';
import { useUser } from './auth/use-user';
import {
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
  useStorage,
} from './provider';

// This function is used to initialize Firebase on the client side.
// It ensures that Firebase is initialized only once.
//
// In development, it will connect to the Firebase Emulator Suite.
function initializeFirebase() {
  const isConfigured = getApps().length > 0;
  const app = isConfigured ? getApp() : initializeApp(firebaseConfig);

  const auth = getAuth(app);
  const firestore = getFirestore(app);
  const storage = getStorage(app);

  if (process.env.NODE_ENV === 'development') {
    if (
      process.env.NEXT_PUBLIC_EMULATOR_HOST &&
      !auth.emulatorConfig
    ) {
      // Point the Auth emulator to the address and port of the local Auth emulator
      //
      // This will get set by the Firebase CLI when running `firebase emulators:start`
      // with the `--import` and `--export-on-exit` flags.
      try {
        connectAuthEmulator(
          auth,
          `http://${process.env.NEXT_PUBLIC_EMULATOR_HOST}:9099`,
          {
            disableWarnings: true,
          }
        );

        console.log('Auth emulator connected');
      } catch (e) {
        console.error(e);
      }
    }

    if (
      process.env.NEXT_PUBLIC_EMULATOR_HOST &&
      // @ts-ignore
      !firestore.emulator
    ) {
      // Point the Firestore emulator to the address and port of the local Firestore emulator
      //
      // This will get set by the Firebase CLI when running `firebase emulators:start`
      // with the `--import` and `--export-on-exit` flags.
      try {
        connectFirestoreEmulator(
          firestore,
          process.env.NEXT_PUBLIC_EMULATOR_HOST,
          8080
        );

        console.log('Firestore emulator connected');
      } catch (e) {
        console.error(e);
      }
    }
    
    if (
        process.env.NEXT_PUBLIC_EMULATOR_HOST &&
        // @ts-ignore
        !storage.emulator
    ) {
        try {
            connectStorageEmulator(
                storage,
                process.env.NEXT_PUBLIC_EMULATOR_HOST,
                9199
            );
            console.log('Storage emulator connected');
        } catch(e) {
            console.error(e);
        }
    }
  }

  return {
    firebaseApp: app,
    firestore,
    auth,
    storage,
  };
}

export {
  initializeFirebase,
  useCollection,
  useDoc,
  useUser,
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
  useStorage,
};
