// DO NOT MODIFY. This file is autogenerated
'use client';

import { useEffect } from 'react';
import { errorEmitter } from '@/firebase/error-emitter';

// This is a global error listener that will catch any Firestore permission errors
// and log them to the console. It is used in the FirebaseProvider.
export function FirebaseErrorListener() {
  useEffect(() => {
    const unsubscribe = errorEmitter.on('permission-error', (error) => {
      // In a production app, you might want to log this to a service like Sentry
      // For now, we'll just log it to the console.
      console.error(error);
    });

    return () => {
      unsubscribe();
    }
  }, []);

  return null;
}
